# src/Auto3D/cli/commands/config.py
"""Configuration management commands."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from rich.panel import Panel
from rich.syntax import Syntax

from Auto3D.cli.config_schema import load_yaml_config
from Auto3D.cli.console import console, print_error, print_success
from Auto3D.constants import (
    DEFAULT_CONVERGENCE_THRESHOLD,
    DEFAULT_OPT_STEPS,
    DEFAULT_PATIENCE,
    DEFAULT_RMSD_THRESHOLD,
)

# Default configuration template
DEFAULT_CONFIG: dict[str, Any] = {
    "path": "input.smi",
    "k": 5,
    "optimizing_engine": "AIMNET",
    "use_gpu": True,
    "gpu_idx": 0,
    "enumerate_tautomer": False,
    "tauto_engine": "rdkit",
    "enumerate_isomer": True,
    "isomer_engine": "rdkit",
    "mpi_np": 4,
    "opt_steps": DEFAULT_OPT_STEPS,
    "convergence_threshold": DEFAULT_CONVERGENCE_THRESHOLD,
    "patience": DEFAULT_PATIENCE,
    "threshold": DEFAULT_RMSD_THRESHOLD,
    "verbose": False,
}

# Preset configurations
PRESETS: dict[str, dict[str, Any]] = {
    "quick": {
        "k": 1,
        "opt_steps": 500,
        "patience": 100,
    },
    "balanced": {
        "k": 5,
        "opt_steps": 2000,
    },
    "thorough": {
        "k": 10,
        "window": 5.0,
        "opt_steps": 5000,
    },
}


def generate_commented_yaml(config: dict) -> str:
    """Generate YAML with helpful comments."""
    lines = ["# Auto3D Configuration File", "# Generated by: auto3d config init", ""]

    comments = {
        "path": "# Input file (required): .smi or .sdf",
        "k": "# Output top-k conformers per molecule",
        "window": "# Energy window in kcal/mol (alternative to k)",
        "optimizing_engine": "# Neural network: AIMNET (recommended), ANI2x, ANI2xt",
        "use_gpu": "# GPU acceleration",
        "gpu_idx": "# GPU device index (0) or list (0,1,2)",
        "enumerate_tautomer": "# Enumerate tautomers",
        "tauto_engine": "# Tautomer engine: rdkit or oechem",
        "enumerate_isomer": "# Enumerate stereoisomers",
        "isomer_engine": "# Isomer engine: rdkit or omega",
        "mpi_np": "# CPU cores for isomer generation",
        "opt_steps": "# Maximum optimization steps",
        "convergence_threshold": "# Force threshold (eV/Angstrom)",
        "patience": "# Steps before dropping oscillating conformer",
        "threshold": "# RMSD threshold for duplicate removal (Angstrom)",
        "verbose": "# Save detailed metadata",
    }

    for key, value in config.items():
        if key in comments:
            lines.append(comments[key])
        lines.append(yaml.dump({key: value}, default_flow_style=False).strip())
        lines.append("")

    return "\n".join(lines)


def execute_config_init(output: Path, preset: str | None = None) -> None:
    """Generate a configuration file."""
    config = DEFAULT_CONFIG.copy()

    if preset:
        if preset not in PRESETS:
            print_error(
                f"Unknown preset: {preset}",
                hint=f"Available presets: {', '.join(PRESETS.keys())}",
            )
            raise SystemExit(1)
        config.update(PRESETS[preset])

    yaml_content = generate_commented_yaml(config)
    output.write_text(yaml_content)

    print_success(f"Created [cyan]{output}[/cyan]")
    console.print()
    console.print(Syntax(yaml_content, "yaml", theme="monokai", line_numbers=True))


def execute_config_show(config_file: Path | None = None) -> None:
    """Display a configuration file with syntax highlighting."""
    if config_file is None:
        config_file = Path("auto3d.yaml")

    if not config_file.exists():
        print_error(
            f"Config file not found: {config_file}",
            hint="Run 'auto3d config init' to create one.",
        )
        raise SystemExit(1)

    content = config_file.read_text()
    console.print(Panel(
        Syntax(content, "yaml", theme="monokai", line_numbers=True),
        title=f"[cyan]{config_file}[/cyan]",
    ))


def execute_config_validate(config_file: Path) -> None:
    """Validate a configuration file."""
    if not config_file.exists():
        print_error(
            f"Config file not found: {config_file}",
            hint="Run 'auto3d config init' to create one.",
        )
        raise SystemExit(1)

    try:
        config = load_yaml_config(config_file)

        # Check required fields
        warnings = []
        if config.k is None and config.window is None:
            warnings.append("Neither 'k' nor 'window' specified - using k=1")

        console.print(Panel(
            f"[green]Valid configuration[/green]\n\n"
            f"Engine: {config.optimizing_engine}\n"
            f"GPU: {'Enabled' if config.use_gpu else 'Disabled'}\n"
            f"Output: {'k=' + str(config.k) if config.k else 'window=' + str(config.window)}",
            title="Validation Passed",
            border_style="green",
        ))

        for warning in warnings:
            console.print(f"[yellow]Warning:[/yellow] {warning}")

    except Exception as e:
        print_error(str(e), hint="Check YAML syntax and field values.")
        raise SystemExit(1)
