# src/Auto3D/cli/commands/config.py
"""Configuration management commands."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from rich.panel import Panel
from rich.syntax import Syntax

from Auto3D.cli.config_schema import load_yaml_config
from Auto3D.cli.console import console, print_success
from Auto3D.cli.errors import handle_error
from Auto3D.constants import (
    DEFAULT_CONVERGENCE_THRESHOLD,
    DEFAULT_OPT_STEPS,
    DEFAULT_PATIENCE,
    DEFAULT_RMSD_THRESHOLD,
)
from Auto3D.exceptions import ConfigurationError

# Default configuration template
DEFAULT_CONFIG: dict[str, Any] = {
    "path": "input.smi",
    "k": 5,
    "optimizing_engine": "AIMNET",
    "use_gpu": True,
    "gpu_idx": 0,
    "enumerate_tautomer": False,
    "tauto_engine": "rdkit",
    "enumerate_isomer": True,
    "isomer_engine": "rdkit",
    "mpi_np": 4,
    "opt_steps": DEFAULT_OPT_STEPS,
    "convergence_threshold": DEFAULT_CONVERGENCE_THRESHOLD,
    "patience": DEFAULT_PATIENCE,
    "threshold": DEFAULT_RMSD_THRESHOLD,
    "verbose": False,
}

# Preset configurations
PRESETS: dict[str, dict[str, Any]] = {
    "quick": {
        "k": 1,
        "opt_steps": 500,
        "patience": 100,
    },
    "balanced": {
        "k": 5,
        "opt_steps": 2000,
    },
    "thorough": {
        # k=10 only -- NOT also window=5.0 (M28). Both were set here before;
        # ConformerRanker.run tested k before window, so k always won and
        # window was silently inert -- and is now rejected outright by
        # Auto3DOptions/CLIConfig if both are set. Kept k rather than
        # switching to window because that is the value every user of this
        # preset has actually been getting since it shipped; picking window
        # instead would be a silent behavior change dressed up as a bug fix.
        "k": 10,
        "opt_steps": 5000,
    },
}


def _require_config_file_exists(config_file: Path) -> None:
    """Raise the standard "config file not found" error if it is missing.

    Both ``execute_config_show`` and ``execute_config_validate`` had this
    exact check (message and hint, word for word) inlined separately.
    """
    if not config_file.exists():
        raise ConfigurationError(
            f"Config file not found: {config_file}",
            hint="Run 'auto3d config init' to create one.",
        )


def generate_commented_yaml(config: dict) -> str:
    """Generate YAML with helpful comments."""
    lines = ["# Auto3D Configuration File", "# Generated by: auto3d config init", ""]

    comments = {
        "path": "# Input file (required): .smi or .sdf",
        "k": "# Output top-k conformers per molecule",
        "window": "# Energy window in kcal/mol (alternative to k)",
        "optimizing_engine": "# Neural network: AIMNET (recommended), ANI2x, ANI2xt",
        "use_gpu": "# GPU acceleration",
        "gpu_idx": "# GPU device index (0) or list (0,1,2)",
        "enumerate_tautomer": "# Enumerate tautomers",
        "tauto_engine": "# Tautomer engine: rdkit or oechem",
        "enumerate_isomer": "# Enumerate stereoisomers",
        "isomer_engine": "# Isomer engine: rdkit or omega",
        "mpi_np": "# CPU cores for isomer generation",
        "opt_steps": "# Maximum optimization steps",
        "convergence_threshold": "# Force threshold (eV/Angstrom)",
        "patience": "# Steps before dropping oscillating conformer",
        "threshold": "# RMSD threshold for duplicate removal (Angstrom)",
        "verbose": "# Save detailed metadata",
    }

    for key, value in config.items():
        if key in comments:
            lines.append(comments[key])
        lines.append(yaml.dump({key: value}, default_flow_style=False).strip())
        lines.append("")

    return "\n".join(lines)


def execute_config_init(
    output: Path, preset: str | None = None, force: bool = False,
    verbose: int = 0,
) -> None:
    """Generate a configuration file.

    Both refusals below are configuration problems, so both leave through
    ``handle_error`` at exit **2**. The overwrite refusal in particular had to
    move: the CLI's own ``-o`` overwrite gate
    (``utils.output_guard.check_output_overwrite``) raises ``ConfigurationError``
    and exits 2, and the CHANGELOG described the two as printing "the same
    message" -- while this one hard-coded ``SystemExit(1)``, so a script
    branching on 2 saw one of them and not the other.
    """
    try:
        # Don't clobber an existing config without explicit consent.
        if output.exists() and not force:
            raise ConfigurationError(
                f"{output} already exists.",
                # Same reason check_output_overwrite suppresses its class
                # hint: "Run 'auto3d config init'" is what the user just ran.
                hint=(
                    "Pass --force/-f to overwrite, or choose a different "
                    "-o path."
                ),
            )

        config = DEFAULT_CONFIG.copy()

        if preset:
            # Unreachable from the CLI, where Typer's `Preset` enum rejects an
            # unknown value as a usage error first (also exit 2). Kept for
            # direct callers of this function, and mapped to the same code the
            # CLI would have produced.
            if preset not in PRESETS:
                raise ConfigurationError(
                    f"Unknown preset: {preset}",
                    hint=f"Available presets: {', '.join(PRESETS.keys())}",
                )
            config.update(PRESETS[preset])

        yaml_content = generate_commented_yaml(config)
        output.write_text(yaml_content)

        print_success(f"Created [cyan]{output}[/cyan]")
        console.print()
        console.print(
            Syntax(yaml_content, "yaml", theme="monokai", line_numbers=True)
        )
    except Exception as e:  # noqa: BLE001 - funnel everything to the error panel
        handle_error(e, verbose=verbose)


def execute_config_show(config_file: Path | None = None, verbose: int = 0) -> None:
    """Display a configuration file with syntax highlighting."""
    try:
        if config_file is None:
            config_file = Path("auto3d.yaml")

        _require_config_file_exists(config_file)

        content = config_file.read_text()

        console.print(Panel(
            Syntax(content, "yaml", theme="monokai", line_numbers=True),
            title=f"[cyan]{config_file}[/cyan]",
        ))
    except Exception as e:  # noqa: BLE001 - funnel everything to the error panel
        handle_error(e, verbose=verbose)


def execute_config_validate(config_file: Path, verbose: int = 0) -> None:
    """Validate a configuration file.

    The exit code must be the one ``auto3d run -c <config_file>`` would give
    for the same file, because predicting that run is this command's only
    purpose. It used to answer every rejection with a hard-coded
    ``SystemExit(1)``, so the identical ``k: 0`` file produced 1 here and 2
    from the run -- a script gating on 2 got the wrong answer from the
    checker. Routing through ``handle_error`` means the exception the runner
    would raise picks the code here too, whatever it is.

    A config file with no ``path`` key is valid here, because it is valid to
    ``auto3d run INPUT -c <file>``: every modern entry point supplies the
    input on the command line and overrides whatever ``path`` the file
    carries. This command used to reject exactly that shape -- the reusable,
    settings-only config -- with ``path / Field required``, so the natural way
    to write a config validated as invalid and then ran fine. See
    ``CLIConfig.path``.
    """
    try:
        # Unreachable from the CLI (Typer's `exists=True` on the argument
        # rejects a missing path as a usage error, also exit 2), but this
        # function is callable directly.
        _require_config_file_exists(config_file)

        config = load_yaml_config(config_file)

        # Conformer selection is required by every entry point, so a config
        # missing both is invalid, not merely incomplete. This used to be a
        # warning saying "using k=1", which was true only of `auto3d run` --
        # and is now true of nothing, since run refuses too. A pre-flight
        # checker that predicts success for a config the runner rejects is
        # worse than no checker.
        if config.k is None and config.window is None:
            raise ConfigurationError(
                "Either k or window needs to be specified. "
                "Usually, setting 'k: 1' satisfies most needs."
            )

        # Say where the input comes from, so "valid" is not mistaken for
        # "complete": a settings-only file is valid for `auto3d run INPUT -c`
        # and invalid for the deprecated `auto3d <config.yaml>` form, which
        # has no other source of an input path.
        input_line = (
            str(config.path) if config.path is not None
            else "supplied on the command line (no 'path' key)"
        )
        console.print(Panel(
            f"[green]Valid configuration[/green]\n\n"
            f"Input: {input_line}\n"
            f"Engine: {config.optimizing_engine}\n"
            f"GPU: {'Enabled' if config.use_gpu else 'Disabled'}\n"
            f"Output: {'k=' + str(config.k) if config.k else 'window=' + str(config.window)}",
            title="Validation Passed",
            border_style="green",
        ))

    except Exception as e:  # noqa: BLE001 - funnel everything to the error panel
        handle_error(e, verbose=verbose)
